# Generated by Django 2.1.13 on 2019-10-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KCC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCliente', models.CharField(max_length=200, verbose_name='Nombre Cliente')),
                ('Latitud', models.FloatField()),
                ('Longitud', models.FloatField()),
                ('Domicilio', models.CharField(max_length=200, verbose_name='Dirección')),
                ('Foto', models.CharField(blank=True, max_length=200, null=True)),
                ('Pedido', models.TextField()),
                ('Precio', models.FloatField()),
            ],
        ),
    ]
